### ISSUE TITLE
Title or Summary for Facebook

### ISSUE THREAD

**Issue by hipstersmoothie** [lukemadera/meteor-social-share#1]
With twitter you can use defaultShareText to put a little text in the tweet. Facebook has the same ability, could you add the ability to attach defaultShareText to a facebook post too?

**Comment by lukemadera** [comment]
@hipstersmoothie as far as I know this is not possible / allowed on Facebook. If you know otherwise, just let me know the URL param to set and I'll add this feature!

http://stackoverflow.com/questions/5023602/facebook-share-body-text

**Comment by ericdtc** [comment]
@lukemadera, using the parameter "t" does actually work, the URL just need to be properly encoded.
http://yourquestions.mcdonalds.ca/ is using it. Click on any question, then on the facebook icon and have a look at the URL of the window that pops up, for instance:
https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fqmcd.ca%2F1L6kMUc&t=is+the+beef+always+going+to+be+bought+from+canadian+farmers%3F
I think the only thing you need to do is to add the following if statement. I can create a pull request if you want, please let me know.

```
ret.link ='https://www.facebook.com/sharer/sharer.php?u=' +
    encodeURIComponent(shareData.url);
    if(shareData.defaultShareText !==undefined) {
      ret.link +='&t='+encodeURIComponent(shareData.defaultShareText)+'%3F';
    }
```

I am not sure why there is an extra "%3F" (that is a question mark) at the and of the URL though.

**Comment by lukemadera** [comment]
@ericdtc The issue was with prompt text, which still is blank for me on the link above.

**Comment by ericdtc** [comment]
@lukemadera, I actually did some tests, and the text 

> Good question! Click through to see how McDonald's Canada answered it.

that does not come from the "t" parameter added to the facebook URL but from the page that is being shared. Adding the "t" parameter does not seem to have any effect..
